FROM prantlf/node-git-chromium:lts-alpine
LABEL maintainer="Ferdinand Prantl <prantlf@gmail.com>"

# From https://github.com/docker-library/openjdk/tree/dd54ae37bc44d19ecb5be702d36d664fed2c68e4
ENV LANG C.UTF-8
ENV JAVA_HOME /usr/lib/jvm/default-jvm/jre
ENV PATH $PATH:/usr/lib/jvm/default-jvm/jre/bin:/usr/lib/jvm/default-jvm/bin
RUN apk --no-cache add openjdk11-jre
